steps:
  - name: maven:3-jdk-14
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-jdk-14
    entrypoint: mvn
    args: ['test']
  - name: maven:3-jdk-14
    entrypoint: mvn
    args: [ 'package','-Dmaven.test.skip=true' ]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/avid-circle-292316/ser-back-end-image", "--build-arg=JAR_FILE=target/ser-back-end-0.0.2.jar", "."]
images: ["gcr.io/avid-circle-292316/ser-back-end-image"]