apiVersion: v1
kind: Service
metadata:
  name: ser-back-end
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: rest
  type: LoadBalancer
  selector:
    app: ser-back-end