package com.github.ser.enums;

public enum DeadlineActivity {

    FILL_COMPANY_DATA,
    CHOOSE_SPONSORSHIP_PACKAGE,
    CHOOSE_ADDITIONAL_EQUIPMENT,
    FILL_CATALOG_INFORMATION,
    SIGN_THE_CONTRACT
}
